<?php

namespace ContainerFnIUxeC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D4QjnYFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D4QjnYF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D4QjnYF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['privates', 'api_platform.validator', 'getApiPlatform_ValidatorService', true],
        ], [
            'manager' => '?',
            'repo' => 'App\\Repository\\UserRepository',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
