<?php

namespace ContainerFnIUxeC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A6KayHRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A6KayHR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A6KayHR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::AddUser' => ['privates', '.service_locator.m4WWrMS', 'get_ServiceLocator_M4WWrMSService', true],
            'App\\Controller\\AdminController::EditAdmin' => ['privates', '.service_locator.D4QjnYF', 'get_ServiceLocator_D4QjnYFService', true],
            'App\\Controller\\ApprenantController::AddUser' => ['privates', '.service_locator.Mz0BfZ_', 'get_ServiceLocator_Mz0BfZService', true],
            'App\\Controller\\ApprenantController::EditAdmin' => ['privates', '.service_locator.D4QjnYF', 'get_ServiceLocator_D4QjnYFService', true],
            'App\\Controller\\CMController::PostCM' => ['privates', '.service_locator..qcDROd', 'get_ServiceLocator__QcDROdService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:AddUser' => ['privates', '.service_locator.m4WWrMS', 'get_ServiceLocator_M4WWrMSService', true],
            'App\\Controller\\AdminController:EditAdmin' => ['privates', '.service_locator.D4QjnYF', 'get_ServiceLocator_D4QjnYFService', true],
            'App\\Controller\\ApprenantController:AddUser' => ['privates', '.service_locator.Mz0BfZ_', 'get_ServiceLocator_Mz0BfZService', true],
            'App\\Controller\\ApprenantController:EditAdmin' => ['privates', '.service_locator.D4QjnYF', 'get_ServiceLocator_D4QjnYFService', true],
            'App\\Controller\\CMController:PostCM' => ['privates', '.service_locator..qcDROd', 'get_ServiceLocator__QcDROdService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::AddUser' => '?',
            'App\\Controller\\AdminController::EditAdmin' => '?',
            'App\\Controller\\ApprenantController::AddUser' => '?',
            'App\\Controller\\ApprenantController::EditAdmin' => '?',
            'App\\Controller\\CMController::PostCM' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:AddUser' => '?',
            'App\\Controller\\AdminController:EditAdmin' => '?',
            'App\\Controller\\ApprenantController:AddUser' => '?',
            'App\\Controller\\ApprenantController:EditAdmin' => '?',
            'App\\Controller\\CMController:PostCM' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
