<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOhSdxwB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOhSdxwB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOhSdxwB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOhSdxwB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOhSdxwB\App_KernelDevDebugContainer([
    'container.build_hash' => 'OhSdxwB',
    'container.build_id' => 'b796da7a',
    'container.build_time' => 1606171788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOhSdxwB');
