<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFnIUxeC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFnIUxeC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFnIUxeC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFnIUxeC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFnIUxeC\App_KernelDevDebugContainer([
    'container.build_hash' => 'FnIUxeC',
    'container.build_id' => '67a2a025',
    'container.build_time' => 1606810568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFnIUxeC');
