<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9QXFWJx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9QXFWJx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9QXFWJx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9QXFWJx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9QXFWJx\App_KernelDevDebugContainer([
    'container.build_hash' => '9QXFWJx',
    'container.build_id' => '7174966d',
    'container.build_time' => 1606319785,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9QXFWJx');
